import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import 'core/router/app_router.dart';
import 'core/theme/app_theme.dart';
import 'features/notifications/data/fcm_service.dart';
import 'firebase_options.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // 1. Load environment variables (Gemini/OpenAI API keys) before anything
  //    else touches Env.* — see lib/config/env/env.dart
  await dotenv.load(fileName: '.env');

  // 2. Initialize Firebase using the platform config generated by
  //    `flutterfire configure` (see firebase_options.dart)
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  // 3. Register the background FCM handler BEFORE runApp — required so
  //    notifications are handled even when the app is fully terminated.
  FirebaseMessaging.onBackgroundMessage(firebaseMessagingBackgroundHandler);

  runApp(const ProviderScope(child: AiStudentAssistantApp()));
}

class AiStudentAssistantApp extends ConsumerStatefulWidget {
  const AiStudentAssistantApp({super.key});

  @override
  ConsumerState<AiStudentAssistantApp> createState() => _AiStudentAssistantAppState();
}

class _AiStudentAssistantAppState extends ConsumerState<AiStudentAssistantApp> {
  @override
  void initState() {
    super.initState();
    // Request notification permission + fetch device token once the app
    // has started. Kept out of main() so it can safely use BuildContext-free
    // async work without blocking app startup.
    FcmService().initialize();
  }

  @override
  Widget build(BuildContext context) {
    final router = ref.watch(appRouterProvider);

    return MaterialApp.router(
      title: 'AI Student Assistant',
      debugShowCheckedModeBanner: false,
      theme: AppTheme.light,
      darkTheme: AppTheme.dark,
      themeMode: ThemeMode.system, // respects the device's dark/light setting
      routerConfig: router,
    );
  }
}
